---
- name: Launch EC2 instances with variables in playbook
  hosts: localhost
  gather_facts: false

  vars:
    region: "us-west-1"
    instance_type: "t2.micro"
    image: "ami-0d1cd67c26f5fca19"   # Replace with your AMI ID
    key_name: "daws-84s"
    security_group: "sg-058c3a47b82e88b3a"
    count: 1
    tag_name: "MyEC2Instance"

  tasks:
    - name: Launch EC2 instance(s)
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        security_groups:
          - "{{ security_group }}"
        count: "{{ count }}"
        wait: yes
        tags:
          Name: "{{ tag_name }}"
      register: ec2

    - name: Show launched instances
      debug:
        var: ec2.instances
