---
- name: Create EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yaml

  tasks:
    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        security_group_ids:
          - "{{ security_group_id }}"
        subnet_id: "{{ subnet_id }}"
        count: "{{ instance_count }}"
        tags:
          Name: "{{ instance_tag_name }}"
      register: ec2_info

    - name: Display instance information
      debug:
        var: ec2_info.instances