---
- name: launch EC2 instance
  hosts: localhost
  connection: local
  vars_files:
    region: us-east-1
    key_name: daws84s
    instance_type: t2.micro
    image_id: ami-09c813fb71547fc4f
    security_group: sg-058c3a47b82e88b3a
    subnet_id: subnet-06c1dd3be6de657c0
    tag_name: Ansible EC2
    count: 1
  tasks:
    - name: launch EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ tag_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        region: "{{ region }}"
        security_group: "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
        wait: yes
        count: "{{ count }}"
        assign_public_ip: yes
      register: ec2

    - name: Show instances info
      debug:
        msg: "EC2 instance launched with ID {{ ec2.instance_ids[0] }}"
