---
- name: Launch EC2 instance
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  vars:
    tag_name: "Ansible EC2"

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image }}"
        region: "{{ region }}"
        security_groups:
          - "{{ security_group }}"
        count: "{{ count }}"
        wait: yes
        tags:
          Name: "{{ tag_name }}"
      register: ec2

    - name: Show launched instances
      debug:
        var: ec2.instances
