- name: create ec2  #creating ec2  
  hosts: local
  connection: local
  vars:
    - vars.yml
  tasks:
  - name: create ec2
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
    register: ec2_output

  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"